name: Deploy to Server

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create deploy.sh script
        run: |
          ssh -o StrictHostKeyChecking=no root@103.146.22.174 "echo '#!/bin/bash
          REPO_URL=\"https://github.com/andrewcaoo/Lake_house_platform.git"  # Replace with your repository URL
          REPO_DIR=\"../../home"  # Replace with the path where you want to clone the repo
          
          if [ ! -d \"\$REPO_DIR\" ]; then
              git clone \"\$REPO_URL\" \"\$REPO_DIR\"
          fi
          
          cd \"\$REPO_DIR\" || exit
          git fetch origin
          if git show-ref --verify --quiet refs/remotes/origin/main; then
              git checkout main
          else
              first_branch=\$(git branch -r | grep -v '\->' | head -n 1 | sed 's/origin\///')
              if [ -n \"\$first_branch\" ]; then
                  git checkout -b main origin/\$first_branch
              else
                  echo \"No branches available to create 'main' from.\"
                  exit 1
              fi
          fi
          
          git pull origin main
          docker-compose up -d --build' > /../../home/Lakehouse/deploy.sh && chmod +x /../../home/Lakehouse/deploy.sh"

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no root@103.146.22.174 "bash /../../home/Lakehouse/deploy.sh"