name: Deploy to Server

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no root@103.146.22.174 "
          REPO_URL='https://github.com/andrewcaoo/Lake_house_platform.git'  # Replace with your repository URL
          REPO_DIR='../../home/Lake_house_platform'  # Replace with the path where you want to clone the repo

          # Check if the repository directory exists
          if [ ! -d \"\$REPO_DIR\" ]; then
              # If it doesn't exist, clone the repository
              git clone \"\$REPO_URL\" \"\$REPO_DIR\"
          fi

          # Navigate to the repository directory
          cd \"\$REPO_DIR\" || exit

          # Fetch all branches from the remote
          git fetch origin

          # Check if the main branch exists on the remote
          if git show-ref --verify --quiet refs/remotes/origin/main; then
              # If the branch exists, check it out
              git checkout main
          else
              # If the branch does not exist, create it from the first available branch
              first_branch=\$(git branch -r | grep -v '\->' | head -n 1 | sed 's/origin\///')
              if [ -n \"\$first_branch\" ]; then
                  git checkout -b main origin/\$first_branch
              else
                  echo \"No branches available to create 'main' from.\"
                  exit 1
              fi
          fi

          # Pull the latest changes
          git pull origin main

          # Build and restart the Docker containers
          docker ps -q | xargs -r docker stop && docker system prune -a -f && docker compose --profile trino --profile spark --profile airflow up -d --build
          "