name: Deploy to Server

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Verify SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no root@103.146.22.174 "echo 'SSH connection successful'"

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no root@103.146.22.174 "cd ../../home/Lakehouse && git pull origin main && docker-compose up -d --build"